# CHAP4 머신러닝에 필요한 수학의 기본

## 4.1 벡터

### 4.1.1 벡터란

- 세로 벡터 : $a = \begin{bmatrix}1\\2\\ \end{bmatrix}$, $b = \begin{bmatrix}2\\1\\ \end{bmatrix}$


- 가로 벡터 : $c = \begin{bmatrix}1&2\\ \end{bmatrix}$, $d = \begin{bmatrix}1&3&5&4\\ \end{bmatrix}$


- 요소 : 벡터를 구성하는 숫자 하나하나.


- 차원 : 벡터가 가지는 요소의 수 eg) **a** : 2차원 세로 벡터, **d** : 4차원 가로 벡터


- 전치(T) : 세로 벡터 $\rightarrow$ 가로 벡터, 가로 벡터 $\rightarrow$ 세로 벡터

    eg ) $a^T = \begin{bmatrix}1\\3\\ \end{bmatrix}^T = \begin{bmatrix}1&3\\ \end{bmatrix}$, $d^T = \begin{bmatrix}1&3&5&4\\ \end{bmatrix}^T = \begin{bmatrix}1\\3\\5\\4\\ \end{bmatrix}$

### 4.1.2 파이썬으로 벡터를 정의하기

In [2]:
import numpy as np
a = np.array([2,1])
print(a, type(a))

[2 1] <class 'numpy.ndarray'>


### 4.1.3 세로 벡터를 나타내기

In [3]:
c = np.array([[1,2],[3,4]]) # 2x2 2차원 ndarray
print(c)

d = np.array([[1], [2]]) # 2x1 2차원 ndarray
print(d)

[[1 2]
 [3 4]]
[[1]
 [2]]


### 4.1.4 전치를 나타내기

In [4]:
print(d.T)

[[1 2]]


### 4.1.5 덧셈과 뺄셈

In [7]:
a = np.array([2, 1])
b = np.array([1, 3])
print(a + b, type(a), type(b), type(a+b)) # list형과 다르게(두 리스트 연결) 각 요소별로 연산.
print(a - b)

[3 4] <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[ 1 -2]


### 4.1.6 스칼라의 곱셈

In [8]:
print(2*a)

[4 2]


### 4.1.7 내적

$b \cdot c = \begin{bmatrix}1\\3\\ \end{bmatrix} \cdot \begin{bmatrix}4\\2\\ \end{bmatrix} = 1\times4 + 3\times2 = 10 $

$w\cdot x = w_0x_0+w_1x_1+\cdots+w_{D-1}x_{D-1} = \sum_{i=0}^{D-1} w_ix_i$

*행렬 표기(벡터 표기) = 성분 표기*

In [9]:
b = np.array([1, 3])
c = np.array([4, 2])
print(b.dot(c))

10


### 4.1.8 벡터의 크기

In [10]:
a = np.array([1, 3])
print(np.linalg.norm(a))

3.1622776601683795


### 4.2.2 합을 내적으로 계산하기


$1 + 2 + \cdots + 1000 = \begin{bmatrix}1\\1\\\vdots\\1\\ \end{bmatrix} \cdot \begin{bmatrix}1\\2\\\vdots\\1000\\ \end{bmatrix} = 1\times1 + 1\times2 + \cdots + 1\times1000 $

In [11]:
import numpy as np
a = np.ones(1000) # [1 1 1 ... 1]
b = np.arange(1, 1001) # [1 2 3 ... 1000]
print(a.dot(b)) # 계산처리가 보다 빠름

500500.0


## 4.4 미분